using TerraScale.MinimalEndpoints.Analyzers.Helpers;
using TerraScale.MinimalEndpoints.Analyzers.Models;
using System.Linq;
using System.Collections.Generic;

namespace TerraScale.MinimalEndpoints.Analyzers.Generators;

internal static class EndpointRegistrationGenerator
{
    public static string GenerateEndpointRegistrationCode(List<EndpointMethod> endpointMethods, List<GroupModel> groups, string assemblyName)
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");

        sb.AppendLine();
        var sanitized = new string(assemblyName.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
        sb.AppendLine($"namespace TerraScale.MinimalEndpoints.Generated_{sanitized};");
        sb.AppendLine();
        sb.AppendLine("public static class MinimalEndpointRegistration");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            sb.AppendLine("public static IServiceCollection AddGeneratedMinimalEndpoints(this IServiceCollection services)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                var distinctClasses = endpointMethods
                    .Select(m => new { m.ClassNamespace, m.ClassName })
                    .Distinct()
                    .OrderBy(x => x.ClassNamespace).ThenBy(x => x.ClassName);

                foreach (var cls in distinctClasses)
                {
                    var fullName = string.IsNullOrEmpty(cls.ClassNamespace) ? cls.ClassName : $"{cls.ClassNamespace}.{cls.ClassName}";
                    sb.AppendLine("// Suppress 'Class is never used' warning - endpoint classes are used by source generator");
                    sb.AppendLine("#pragma warning disable CS0169");
                    sb.AppendLine($"services.AddScoped<{fullName}>();");
                    sb.AppendLine("#pragma warning restore CS0169");
                }

                sb.AppendLine("return services;");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("public static void MapGeneratedMinimalEndpoints(this IEndpointRouteBuilder endpoints)");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                if (endpointMethods.Count == 0)
                {
                    sb.AppendLine("// No endpoints found to register");
                }
                else
                {
                    // Group endpoints by GroupTypeFullName
                    // Use a stable sort order
                    var groupedEndpoints = endpointMethods
                        .GroupBy(m => m.GroupTypeFullName)
                        .OrderBy(g => g.Key ?? string.Empty);

                    int groupCounter = 0;

                    foreach (var group in groupedEndpoints)
                    {
                        string builderName = "endpoints";

                        // Check if this is a named group
                        if (!string.IsNullOrEmpty(group.Key))
                        {
                            var groupModel = groups.FirstOrDefault(g => g.TypeFullName == group.Key);
                            if (groupModel != null)
                            {
                                builderName = $"group_{groupCounter++}";
                                sb.AppendLine();
                                sb.AppendLine($"// Group: {groupModel.ClassName}");
                                sb.AppendLine($"var {builderName} = endpoints.MapGroup(new {groupModel.TypeFullName}().RoutePrefix);");
                                sb.AppendLine($"new {groupModel.TypeFullName}().Configure({builderName});");

                                // Apply attributes
                                if (groupModel.HasAuthorize)
                                {
                                     // Let's assume we use object initializer on AuthorizeAttribute
                                     var authLine = new System.Text.StringBuilder();
                                     authLine.Append($"{builderName}.RequireAuthorization(new Microsoft.AspNetCore.Authorization.AuthorizeAttribute");
                                     var props = new List<string>();
                                     if (!string.IsNullOrEmpty(groupModel.Policy)) props.Add($"Policy = \"{EscapeString(groupModel.Policy)}\"");
                                     if (!string.IsNullOrEmpty(groupModel.Roles)) props.Add($"Roles = \"{EscapeString(groupModel.Roles)}\"");
                                     if (!string.IsNullOrEmpty(groupModel.AuthenticationSchemes)) props.Add($"AuthenticationSchemes = \"{EscapeString(groupModel.AuthenticationSchemes)}\"");

                                     if (props.Any())
                                     {
                                         authLine.Append($" {{ {string.Join(", ", props)} }}");
                                     }
                                     authLine.Append(");");
                                     sb.AppendLine(authLine.ToString());
                                }

                                if (groupModel.HasAllowAnonymous)
                                {
                                    sb.AppendLine($"{builderName}.AllowAnonymous();");
                                }

                                // Group Name
                                if (!string.IsNullOrEmpty(groupModel.EndpointGroupNameAttributeValue))
                                {
                                    sb.AppendLine($"{builderName}.WithGroupName(\"{EscapeString(groupModel.EndpointGroupNameAttributeValue)}\");");
                                }
                                else
                                {
                                    sb.AppendLine($"{builderName}.WithGroupName(new {groupModel.TypeFullName}().Name);");
                                }

                                // Tags
                                if (groupModel.Tags.Any())
                                {
                                    var tagsArgs = string.Join(", ", groupModel.Tags.Select(t => $"\"{EscapeString(t)}\""));
                                    sb.AppendLine($"{builderName}.WithTags(new[] {{ {tagsArgs} }})");
                                    sb.AppendLine($"    .WithTags(new {groupModel.TypeFullName}().Name);");
                                }
                                else
                                {
                                    sb.AppendLine($"{builderName}.WithTags(new {groupModel.TypeFullName}().Name);");
                                }

                                // Filters
                                foreach (var filter in groupModel.EndpointFilters)
                                {
                                    sb.AppendLine($"{builderName}.AddEndpointFilter<{filter}>();");
                                }
                            }
                        }

                        foreach (var method in group)
                        {
                            GenerateMethodRegistration(sb, method, builderName);
                        }
                    }
                }
            }
            sb.AppendLine("}");
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateMethodRegistration(IndentedStringBuilder sb, EndpointMethod method, string builderName)
    {
        sb.AppendLine();
        sb.AppendLine($"// Register {method.ClassName}.{method.MethodName}");
        sb.AppendLine("{");

        using (sb.Indent())
        {
            string routePattern;
            if (!method.HasExplicitRoute && string.IsNullOrEmpty(method.Route))
            {
                routePattern = $"/{method.ClassName}/{method.MethodName}";
            }
            else if (string.IsNullOrEmpty(method.Route))
            {
                routePattern = string.Empty;
            }
            else
            {
                routePattern = method.Route.StartsWith("/") ? method.Route : $"/{method.Route}";
            }

            var pascalHttpMethod = method.HttpMethod?.ToString() ?? string.Empty;
            var lambdaParams = new List<string>();

            // Inject the instance itself
            var instanceType = string.IsNullOrEmpty(method.ClassNamespace) ? method.ClassName : $"{method.ClassNamespace}.{method.ClassName}";
            lambdaParams.Add($"[Microsoft.AspNetCore.Mvc.FromServices] {instanceType} instance");

            var httpContextParam = method.Parameters.FirstOrDefault(p => p.Type.EndsWith("HttpContext"));
            var httpContextVarName = httpContextParam?.Name ?? "httpContext";

            foreach (var param in method.Parameters)
            {
                var attributes = new List<string>();
                if (param.IsFromServices) attributes.Add("[Microsoft.AspNetCore.Mvc.FromServices]");
                if (param.IsFromBody) attributes.Add("[Microsoft.AspNetCore.Mvc.FromBody]");
                if (param.IsFromQuery) attributes.Add("[Microsoft.AspNetCore.Mvc.FromQuery]");
                if (param.IsFromRoute) attributes.Add("[Microsoft.AspNetCore.Mvc.FromRoute]");
                if (param.IsFromHeader)
                {
                    if (!string.IsNullOrEmpty(param.FromHeaderName))
                        attributes.Add($"[Microsoft.AspNetCore.Mvc.FromHeader(Name = \"{EscapeString(param.FromHeaderName)}\")]");
                    else
                        attributes.Add("[Microsoft.AspNetCore.Mvc.FromHeader]");
                }
                if (param.IsFromForm) attributes.Add("[Microsoft.AspNetCore.Mvc.FromForm]");

                var attrString = attributes.Any() ? string.Join(" ", attributes) + " " : "";
                lambdaParams.Add($"{attrString}{param.Type} {param.Name}");
            }

            if (httpContextParam == null)
            {
                lambdaParams.Add($"HttpContext {httpContextVarName}");
            }

            sb.AppendLine($"var builder = {builderName}.Map{pascalHttpMethod}(\"{routePattern}\", async (");
            sb.AppendLine($"    {string.Join(", ", lambdaParams)}) =>");

            sb.AppendLine("{");
            using (sb.Indent())
            {
                sb.AppendLine($"if (instance is TerraScale.MinimalEndpoints.BaseMinimalApiEndpoint baseEp)");
                sb.AppendLine("{");
                using (sb.Indent())
                {
                    sb.AppendLine($"baseEp.Context = {httpContextVarName};");
                }
                sb.AppendLine("}");

                var methodCallParams = string.Join(", ", method.Parameters.Select(p => p.Name));

                if (method.ReturnType.Contains("Task"))
                {
                    sb.AppendLine($"return await instance.{method.MethodName}({methodCallParams});");
                }
                else
                {
                    sb.AppendLine($"return instance.{method.MethodName}({methodCallParams});");
                }
            }
            sb.AppendLine("});");

            if (!string.IsNullOrEmpty(method.Summary))
            {
                sb.AppendLine($"builder.WithName(\"{EscapeString(method.MethodName)}\");");
                sb.AppendLine($"builder.WithSummary(\"{EscapeString(method.Summary)}\");");
            }

            if (!string.IsNullOrEmpty(method.Description))
            {
                sb.AppendLine($"builder.WithDescription(\"{EscapeString(method.Description)}\");");
            }

            var allTags = new List<string>();
            if (method.Tags.Any())
            {
                allTags.AddRange(method.Tags);
            }

            if (allTags.Any())
            {
                var tagsArray = string.Join(", ", allTags.Select(t => $"\"{EscapeString(t)}\""));
                sb.AppendLine($"builder.WithTags(new[] {{ {tagsArray} }});");
            }

            if (!string.IsNullOrEmpty(method.GroupName) && method.GroupName != method.ClassName)
            {
                sb.AppendLine($"builder.WithGroupName(\"{EscapeString(method.GroupName)}\");");
            }

            foreach (var prod in method.Produces)
            {
                 var first = prod.ContentTypes.FirstOrDefault() ?? "application/json";
                 var others = prod.ContentTypes.Skip(1).Select(p => $"\"{EscapeString(p)}\"").ToList();
                 var othersArg = others.Any() ? ", " + string.Join(", ", others) : "";
                 var responseType = !string.IsNullOrEmpty(prod.ResponseType) ? $"typeof({prod.ResponseType})" : $"typeof({method.ReturnTypeInner})";

                 sb.AppendLine($"builder.Produces({prod.StatusCode}, {responseType}, \"{EscapeString(first)}\"{othersArg});");
            }

            if (method.Consumes.Any())
            {
                var bodyParam = method.Parameters.FirstOrDefault(p => p.IsFromBody);
                var typeString = bodyParam != null ? $"typeof({bodyParam.Type})" : "typeof(object)";

                var first = method.Consumes[0];
                var others = method.Consumes.Skip(1).Select(c => $"\"{EscapeString(c)}\"").ToList();
                var othersArg = others.Any() ? ", " + string.Join(", ", others) : "";

                sb.AppendLine($"builder.Accepts({typeString}, \"{EscapeString(first)}\"{othersArg});");
            }

            foreach (var response in method.ResponseDescriptions)
            {
                 var typeToUse = response.Key == 200 ? $"typeof({method.ReturnTypeInner})" : "typeof(void)";
                 sb.AppendLine($"builder.Produces({response.Key}, {typeToUse});");
            }

            if (method.ParameterDescriptions.Any())
            {
                sb.AppendLine("#pragma warning disable ASPDEPR002");
                sb.AppendLine("builder.WithOpenApi(op => {");
                sb.AppendLine("    if (op.Parameters != null)");
                sb.AppendLine("    {");
                foreach (var paramDesc in method.ParameterDescriptions)
                {
                    sb.AppendLine($"        var param_{paramDesc.Key} = op.Parameters.FirstOrDefault(p => p.Name == \"{EscapeString(paramDesc.Key)}\");");
                    sb.AppendLine($"        if (param_{paramDesc.Key} != null) param_{paramDesc.Key}.Description = \"{EscapeString(paramDesc.Value)}\";");
                }
                sb.AppendLine("    }");
                sb.AppendLine("    return op;");
                sb.AppendLine("});");
                sb.AppendLine("#pragma warning restore ASPDEPR002");
            }

            if (method.IsDeprecated)
            {
                sb.AppendLine("#pragma warning disable ASPDEPR002");
                sb.AppendLine($"builder.WithOpenApi(op => {{ op.Deprecated = true; return op; }});");
                sb.AppendLine("#pragma warning restore ASPDEPR002");
            }

            if (method.HasAllowAnonymous)
            {
                sb.AppendLine("builder.AllowAnonymous();");
            }

            if (method.HasAuthorize)
            {
                 var authLine = new System.Text.StringBuilder();
                 authLine.Append("builder.RequireAuthorization(new Microsoft.AspNetCore.Authorization.AuthorizeAttribute");
                 var props = new List<string>();
                 if (!string.IsNullOrEmpty(method.Policy)) props.Add($"Policy = \"{EscapeString(method.Policy)}\"");
                 if (!string.IsNullOrEmpty(method.Roles)) props.Add($"Roles = \"{EscapeString(method.Roles)}\"");
                 if (!string.IsNullOrEmpty(method.AuthenticationSchemes)) props.Add($"AuthenticationSchemes = \"{EscapeString(method.AuthenticationSchemes)}\"");

                 if (props.Any())
                 {
                     authLine.Append($" {{ {string.Join(", ", props)} }}");
                 }
                 authLine.Append(");");
                 sb.AppendLine(authLine.ToString());
            }

            foreach (var filter in method.EndpointFilters)
            {
                sb.AppendLine($"builder.AddEndpointFilter<{filter}>();");
            }

            if (method.HasConfigureMethod)
            {
                 var typeName = string.IsNullOrEmpty(method.ClassNamespace) ? method.ClassName : $"{method.ClassNamespace}.{method.ClassName}";
                 sb.AppendLine($"{typeName}.Configure(builder);");
            }
        }
        sb.AppendLine("}");
    }

    private static string EscapeString(string? input)
    {
        if (string.IsNullOrEmpty(input))
            return string.Empty;

        return input!.Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
    }
}
